import {
  MD3LightTheme,
  MD3DarkTheme,
  configureFonts,
} from "react-native-paper";
import { Platform } from "react-native";

// Font configuration
const fontConfig = {
  displayLarge: {
    fontFamily: "Inter_700Bold",
    fontSize: 57,
    fontWeight: "700",
    letterSpacing: 0,
    lineHeight: 64,
  },
  displayMedium: {
    fontFamily: "Inter_700Bold",
    fontSize: 45,
    fontWeight: "700",
    letterSpacing: 0,
    lineHeight: 52,
  },
  displaySmall: {
    fontFamily: "Inter_700Bold",
    fontSize: 36,
    fontWeight: "700",
    letterSpacing: 0,
    lineHeight: 44,
  },
  headlineLarge: {
    fontFamily: "Inter_700Bold",
    fontSize: 32,
    fontWeight: "700",
    letterSpacing: 0,
    lineHeight: 40,
  },
  headlineMedium: {
    fontFamily: "Inter_600SemiBold",
    fontSize: 28,
    fontWeight: "600",
    letterSpacing: 0,
    lineHeight: 36,
  },
  headlineSmall: {
    fontFamily: "Inter_600SemiBold",
    fontSize: 24,
    fontWeight: "600",
    letterSpacing: 0,
    lineHeight: 32,
  },
  titleLarge: {
    fontFamily: "Inter_600SemiBold",
    fontSize: 22,
    fontWeight: "600",
    letterSpacing: 0,
    lineHeight: 28,
  },
  titleMedium: {
    fontFamily: "Inter_600SemiBold",
    fontSize: 16,
    fontWeight: "600",
    letterSpacing: 0.15,
    lineHeight: 24,
  },
  titleSmall: {
    fontFamily: "Inter_600SemiBold",
    fontSize: 14,
    fontWeight: "600",
    letterSpacing: 0.1,
    lineHeight: 20,
  },
  labelLarge: {
    fontFamily: "Inter_600SemiBold",
    fontSize: 14,
    fontWeight: "600",
    letterSpacing: 0.1,
    lineHeight: 20,
  },
  labelMedium: {
    fontFamily: "Inter_600SemiBold",
    fontSize: 12,
    fontWeight: "600",
    letterSpacing: 0.5,
    lineHeight: 16,
  },
  labelSmall: {
    fontFamily: "Inter_600SemiBold",
    fontSize: 11,
    fontWeight: "600",
    letterSpacing: 0.5,
    lineHeight: 16,
  },
  bodyLarge: {
    fontFamily: "Inter_400Regular",
    fontSize: 16,
    fontWeight: "400",
    letterSpacing: 0.15,
    lineHeight: 24,
  },
  bodyMedium: {
    fontFamily: "Inter_400Regular",
    fontSize: 14,
    fontWeight: "400",
    letterSpacing: 0.25,
    lineHeight: 20,
  },
  bodySmall: {
    fontFamily: "Inter_400Regular",
    fontSize: 12,
    fontWeight: "400",
    letterSpacing: 0.4,
    lineHeight: 16,
  },
  default: {
    fontFamily: "Inter_400Regular",
  },
} as const;

// Custom Teal/Cyan Palette (Material You Style)
const lightColors = {
  ...MD3LightTheme.colors,
  primary: "#006A6A",
  onPrimary: "#FFFFFF",
  primaryContainer: "#6FF7F6",
  onPrimaryContainer: "#002020",
  secondary: "#4A6363",
  onSecondary: "#FFFFFF",
  secondaryContainer: "#CCE8E7",
  onSecondaryContainer: "#051F1F",
  tertiary: "#4B607C",
  onTertiary: "#FFFFFF",
  tertiaryContainer: "#D3E4FF",
  onTertiaryContainer: "#041C35",
  error: "#BA1A1A",
  onError: "#FFFFFF",
  errorContainer: "#FFDAD6",
  onErrorContainer: "#410002",
  background: "#FAFDFC",
  onBackground: "#191C1C",
  surface: "#FAFDFC",
  onSurface: "#191C1C",
  surfaceVariant: "#DAE4E4",
  onSurfaceVariant: "#3F4948",
  outline: "#6F7979",
  outlineVariant: "#BEC8C8",
  shadow: "#000000",
  scrim: "#000000",
  inverseSurface: "#2D3131",
  inverseOnSurface: "#EFF1F0",
  inversePrimary: "#4CDADA",
  elevation: {
    level0: "transparent",
    level1: "#F0F5F4",
    level2: "#EBF1F0",
    level3: "#E5EDEC",
    level4: "#E3ECEB",
    level5: "#DFEAE9",
  },
  surfaceDisabled: "rgba(25, 28, 28, 0.12)",
  onSurfaceDisabled: "rgba(25, 28, 28, 0.38)",
  backdrop: "rgba(41, 50, 50, 0.4)",
};

const darkColors = {
  ...MD3DarkTheme.colors,
  primary: "#4CDADA",
  onPrimary: "#003737",
  primaryContainer: "#004F4F",
  onPrimaryContainer: "#6FF7F6",
  secondary: "#B0CCCB",
  onSecondary: "#1B3434",
  secondaryContainer: "#334B4B",
  onSecondaryContainer: "#CCE8E7",
  tertiary: "#B3C8E8",
  onTertiary: "#1C314C",
  tertiaryContainer: "#334863",
  onTertiaryContainer: "#D3E4FF",
  error: "#FFB4AB",
  onError: "#690005",
  errorContainer: "#93000A",
  onErrorContainer: "#FFDAD6",
  background: "#191C1C",
  onBackground: "#E0E3E3",
  surface: "#191C1C",
  onSurface: "#E0E3E3",
  surfaceVariant: "#3F4948",
  onSurfaceVariant: "#BEC8C8",
  outline: "#889392",
  outlineVariant: "#3F4948",
  shadow: "#000000",
  scrim: "#000000",
  inverseSurface: "#E0E3E3",
  inverseOnSurface: "#2D3131",
  inversePrimary: "#006A6A",
  elevation: {
    level0: "transparent",
    level1: "#1C2626",
    level2: "#202C2C",
    level3: "#263131",
    level4: "#273333",
    level5: "#2B3737",
  },
  surfaceDisabled: "rgba(224, 227, 227, 0.12)",
  onSurfaceDisabled: "rgba(224, 227, 227, 0.38)",
  backdrop: "rgba(41, 50, 50, 0.4)",
};

export const theme = {
  light: {
    ...MD3LightTheme,
    fonts: configureFonts({ config: fontConfig }),
    colors: lightColors,
  },
  dark: {
    ...MD3DarkTheme,
    fonts: configureFonts({ config: fontConfig }),
    colors: darkColors,
  },
};
